__default__:
  partition: progress,standard
  walltime: 24:00:00   # walltime limit for each job
  cpus_per_task: 16   # number of cores per job
  mem_mb: 124000  # Increased memory allocation
  exclude: gpu0.omnia.cluster,gpu1.omnia.cluster,gpu2.omnia.cluster
  output: logs/{rule}/log-%j.out
  error: logs/{rule}/errlog-%j.err

# build_solar_thermal_profiles:
#   partition: progress
#   walltime: 12:00:00
#   cpus_per_task: 8
#   mem_mb: 64000  # Specific memory allocation for this rule
#   exclude: gpu0.omnia.cluster,gpu1.omnia.cluster,gpu2.omnia.cluster

# Node	CPU	Max MHz	Cores	Partition
# gpu0	Intel Xeon Gold 6438M	3900	128	standard
# gpu3	AMD EPYC 9654	3708	384	standard
# cpu0–cpu5	AMD EPYC 7763	3529	256	progress/standard
# gpu2	AMD EPYC 7662	2154	256	progress/standard
# gpu1	AMD EPYC 7662	2154	256	standard