# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.6.0
tutorial: false

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

results_dir: results/
summary_dir: results/

foresight: overnight

countries: ["MA"]
# Can be replaced by country ["NG", "BJ"], continent ["Africa"] or user-specific region, see more at https://pypsa-earth.readthedocs.io/en/latest/configuration.html#top-level-configuration

enable:
  retrieve_databundle: true # Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: true
  retrieve_cost_data: true # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: true # If 'true', OpenStreetMap data will be downloaded for the above given countries
  build_natura_raster: false # If True, then an exclusion raster will be build
  build_cutout: false
  # If "build_cutout" : true, then environmental data is extracted according to `snapshots` date range and `countries`
  # requires cds API key https://cds.climate.copernicus.eu/api-how-to
  # More information https://atlite.readthedocs.io/en/latest/introduction.html#datasets
  progress_bar: true # show progress bar during downloading routines and other long-running tasks



custom_rules: [] # Default empty [] or link to custom rule file e.g. ["my_folder/my_rules.smk"] that add rules to Snakefile

run:
  name: "MA_H2G_B_250515" # use this to keep track of runs with different settings
  sector_name: "MA_H2G_B_250515" # use this to keep track of sector scenario runs
  shared_cutouts: true # set to true to share the default cutout(s) across runs
  # Note: value false requires build_cutout to be enabled
  allow_scenario_failure: false # If True, the workflow will continue even if a scenario in run_scnenario fails

scenario:
  simpl: [""]
  ll: ["copt"]
  clusters: [3flex] # TODO: Define which GADM vs. Aggregated data from REGIOANTS
  opts: [Co2L0.83] # 2030, 2035, ...: Co2L0.83, Co2L0.62,	Co2L0.46,	Co2L0.35.NOTES: Hourly resolution is considered in solve rules (elec)
  planning_horizons: # investment years for myopic and perfect; or costs year for overnight
  - 2030
  #- 2050 # TODO: Can I add several years here??
  sopts: # NOTES: this is for sector options
  - "1h" # TODO: Should we set a different resolution??
  demand:
  - "MA-GNZ-IEE" # NB: Use "MA-GNZ-IEE" if custom_demands.update_data = true and "GNZ" if custom_demands.update_data = false

snapshots: 
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: "left" # end is not inclusive


augmented_line_connection: # TODO: For Morocco there are plans to be interconected with Europe, i.e. Spain
  add_to_snakefile: false # If True, includes this rule to the workflow
  connectivity_upgrade: 2 # Min. lines connection per node,
  # https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation.html#networkx.algorithms.connectivity.edge_augmentation.k_edge_augmentation
  new_line_type: ["HVAC"] # Expanded lines can be either ["HVAC"] or ["HVDC"] or both ["HVAC", "HVDC"]
  min_expansion: 1 # [MW] New created line expands by float/int input
  min_DC_length: 600 # [km] Minimum line length of DC line


subregion:
  define_by_gadm: false # name of the subregion. Multiple countries can be part in the same subregion.
    # MA0 : [MA.6_1, MA.7_1]
    # MA1 : [MA.1_1, MA.2_1, MA.5_1, MA.8_1, MA.12_1, MA.13_1]
    # MA2 : [MA.3_1, MA.4_1, MA.9_1, MA.10_1, MA.11_1, MA.14_1, MA.15_1]
  path_custom_shapes: 
    "/mnt/data/gsa/pypsa-earth-custom-lukas/data/custom/agg_3_nodes_esm_regions_mar.geojson" # (optional) provide the specific absolute path of the custom file e.g. (...\data\custom_shapes.geojson)
  

electricity:
  #co2limit: 114.0e+6 # European default, 0.05 * 3.1e9*0.5, needs to be adjusted for Africa
  co2base: 63.80e+6 # TODO per country: adjust using excel file and value for 2015 based on https://edgar.jrc.ec.europa.eu/dataset_ghg2024.

costs:
  year: 2030
  version: v0.10.0
  discountrate: [0.071] #, 0.086, 0.111]

policy_config:
  hydrogen: #TODO: ESTEFANIA CHECK WHAT DOES IT MEANS THE HOURLY MATCHING
    temporal_matching: "no_res_matching" # either "h2_yearly_matching", "h2_monthly_matching", "no_res_matching"
    spatial_matching: false
    additionality: true # RE electricity is equal to the amount required for additional hydrogen export compared to the 0 export case ("reference_case")
    allowed_excess: 1.0
    is_reference: false # Whether or not this network is a reference case network, relevant only if additionality is _true_
    remove_h2_load: false #Whether or not to remove the h2 load from the network, relevant only if is_reference is _true_
    path_to_ref: "" # Path to the reference case network for additionality calculation, relevant only if additionality is _true_ and is_reference is _false_
    re_country_load: false # Set to "True" to force the RE electricity to be equal to the electricity required for hydrogen export and the country electricity load. "False" excludes the country electricity load from the constraint.


fossil_reserves:
  oil: 100 #TWh Maybe redundant

export:
  endogenous: false # If true, the export demand is endogenously determined by the model
  endogenous_price: 400 # EUR/MWh # Market price, for wich the hydrogen for endogenous exports is sold. Only considered, if ["export"]["endogenous"] is set to true.
  store: true # [True, False] # specifies whether an export store to balance demand is implemented
  store_capital_costs: "no_costs" # ["standard_costs", "no_costs"] # specifies the costs of the export store. "standard_costs" takes CAPEX of "hydrogen storage tank type 1 including compressor"
  h2export: [3.33, 10.0] # Yearly export demand in TWh. Only considered, if ["export"]["endogenous"] is set to false
  export_profile: "constant" # use "ship" or "constant". Only considered, if ["export"]["endogenous"] is set to false
  ship:
    ship_capacity: 0.4 # TWh # 0.05 TWh for new ones, 0.003 TWh for Susio Frontier, 0.4 TWh according to Hampp2021: "Corresponds to 11360 t H2 (l) with LHV of 33.3333 Mwh/t_H2. Cihlar et al 2020 based on IEA 2019, Table 3-B"
    travel_time: 288 # hours # From Agadir to Rotterdam and back (12*24)
    fill_time: 24 # hours, for 48h see Hampp2021
    unload_time: 24 # hours for 48h see Hampp2021

custom_data:
  renewables: # ['csp', 'rooftop-solar', 'solar']
    update_data: false
    res_techs: ["solar","onwind"] # ['csp', 'rooftop-solar', 'solar']
  elec_demand: false
  heat_demand: false
  industry_demand: false
  industry_database: false
  transport_demand: false
  water_costs: false
  h2_underground: false
  add_existing: false
  custom_sectors: false
  custom_demands: # TODO: ESTEFANIA ADD THE WORKFLOW FOR DEMAND DATA TOO
    update_data: true # if true then custom .csv file must be placed in "data/custom/energy_tatals_{w.demand}_{w.planning_horizons}.csv", If "False" the workflow works with default data.
    # altdemands: "MA_iee_GlobalNZ" #"MA_NH2Strategy","MA_iee_baseline" if "True" then custom .csv file must be placed in "data/custom/xxxx.csv" , If "False" the workflow works with default data.
  gas_network: false # If "True" then a custom .csv file must be placed in "resources/custom_data/pipelines.csv" , If "False" the user can choose btw "greenfield" or Model built-in datasets. Please refer to ["sector"] below.
  export_ports: false # If "True" then a custom .csv file must be placed in "data/custom/export_ports.csv"
  airports: false # If "True" then a custom .csv file must be placed in "data/custom/airports.csv". Data format for aiports must be in the format of the airports.csv file in the data folder.

industry:
  reference_year: 2015


sector:
  gas:
    spatial_gas: true # ALWAYS TRUE
    network: false # ALWAYS FALSE for now (NOT USED)
    network_data: GGIT # Global dataset -> 'GGIT' , European dataset -> 'IGGIELGN'
    network_data_GGIT_status: ["Construction", "Operating", "Idle", "Shelved", "Mothballed", "Proposed"]
  hydrogen:
    network: true
    H2_retrofit_capacity_per_CH4: 0.6
    network_limit: 2000 #GWkm #TODO: TALK WITH LUKAS
    network_routes: greenfield # "gas or "greenfield". If "gas"  ->  the network data are fetched from ["sector"]["gas"]["network_data"]. If "greenfield"  -> the network follows the topology of electrical transmission lines
    gas_network_repurposing: false # If true -> ["sector"]["gas"]["network"] is automatically false
    underground_storage: false
    hydrogen_colors: false
    set_color_shares: false
    blue_share: 0.40
    pink_share: 0.05
  coal:
    spatial_coal: true
    shift_to_elec: true # If true, residential and services demand of coal is shifted to electricity. If false, the final energy demand of coal is disregarded
  lignite:
    spatial_lignite: false

  international_bunkers: true #Whether or not to count the emissions of international aviation and navigation

  oil:
    spatial_oil: true

  district_heating:
    potential: 0.2 #maximum fraction of urban demand which can be supplied by district heating
    #increase of today's district heating demand to potential maximum district heating share
    #progress = 0 means today's district heating share, progress=-1 means maximum fraction of urban demand is supplied by district heating
    progress:
      2020: 0.0
      2030: 0.3
      2040: 0.6
      2050: 1.0
    district_heating_loss: 0.15
  reduce_space_heat_exogenously: true # reduces space heat demand by a given factor (applied before losses in DH)
  # this can represent e.g. building renovation, building demolition, or if
  # the factor is negative: increasing floor area, increased thermal comfort, population growth
  reduce_space_heat_exogenously_factor: # per unit reduction in space heat demand
  # the default factors are determined by the LTS scenario from http://tool.european-calculator.eu/app/buildings/building-types-area/?levers=1ddd4444421213bdbbbddd44444ffffff11f411111221111211l212221
    2020: 0.10  # this results in a space heat demand reduction of 10%
    2025: 0.09  # first heat demand increases compared to 2020 because of larger floor area per capita
    2030: 0.09
    2035: 0.11
    2040: 0.16
    2045: 0.21
    2050: 0.29

  v2g: false #allows feed-in to grid from EV battery (vehicle-to-grid) #TODO: TALK WITH LUKAS

  biomass_transport: true # biomass transport between nodes
  biomass_transport_default_cost: 0.1 #EUR/km/MWh
  solid_biomass_potential: 17.1 # TWh/a, Potential of whole modelled area 
  # TODO per country: conservative assumptions is to take 97% of biofuel/bioenergy from https://unstats.un.org/unsd/energystats/dataPortal/, divide value by 3600 TJ/TWh
  biogas_potential: 0.5 # TWh/a, Potential of whole modelled area 
  # TODO per country: conservative assumptions is to take 3% of biofuel/bioenergy from https://unstats.un.org/unsd/energystats/dataPortal/, divide value by 3600 TJ/TWh

  efficiency_heat_oil_to_elec: 0.9
  efficiency_heat_biomass_to_elec: 0.9
  efficiency_heat_gas_to_elec: 0.9

  electricity_distribution_grid: false # adds low voltage buses and shifts AC loads, BEVs, heat pumps, and resistive heaters, micro CHPs to low voltage buses if technologies are present
  solar_rooftop: false # adds distribution side customer rooftop PV (only work if electricity_distribution_grid: true)
  home_battery: true # adds home batteries to low voltage buses ((only work if electricity_distribution_grid: true)
  transmission_efficiency:
    electricity distribution grid:
      efficiency_static: 0.97 # efficiency of distribution grid (i.e. 3% loses)
    H2 pipeline:
      efficiency_per_1000km: 1
      compression_per_1000km: 0.017 # DEA technology data. Mean of  Energy losses, lines 5000-20000 MW and lines >20000 MW for 2020, 2030 and 2050, [%/1000 km]

  dynamic_transport:
    enable: false # If "True", then the BEV and FCEV shares are obtained depending on the "Co2L"-wildcard (e.g. "Co2L0.70: 0.10"). If "False", then the shares are obtained depending on the "demand" wildcard and "planning_horizons" wildcard as listed below (e.g. "DF_2050: 0.08")
    land_transport_electric_share:
      Co2L2.0: 0.00
      Co2L1.0: 0.01
      Co2L0.90: 0.03
      Co2L0.80: 0.06
      Co2L0.70: 0.10
      Co2L0.60: 0.17
      Co2L0.50: 0.27
      Co2L0.40: 0.40
      Co2L0.30: 0.55
      Co2L0.20: 0.69
      Co2L0.10: 0.80
      Co2L0.00: 0.88
    land_transport_fuel_cell_share:
      Co2L2.0: 0.01
      Co2L1.0: 0.01
      Co2L0.90: 0.01
      Co2L0.80: 0.01
      Co2L0.70: 0.01
      Co2L0.60: 0.01
      Co2L0.50: 0.01
      Co2L0.40: 0.01
      Co2L0.30: 0.01
      Co2L0.20: 0.01
      Co2L0.10: 0.01
      Co2L0.00: 0.01

  land_transport_fuel_cell_share: # 1 means all FCEVs HERE
    NH2S_2030: 0.05 # based on Morocco H2 strategy (reference scenario)
    GNZ_2030: 0.04 # based on IEA scenarios
    NH2S_2050: 0.10 # based on Morocco H2 strategy (reference scenario)
    GNZ_2050: 0.19 # based on IEA scenarios
    MA-NH2S-IEE_2030: 0.05 # based on Morocco H2 strategy (reference scenario)
    MA-GNZ-IEE_2030: 0.04 # based on IEA scenarios
    MA-NH2S-IEE_2050: 0.10 # based on Morocco H2 strategy (reference scenario)
    MA-GNZ-IEE_2050: 0.19 # based on IEA scenarios
    # https://www.iea.org/reports/road-transport#dashboard. Slightly lower values compared to global average.
    # TODO per country: Double check for next iterations
    # land transport includes road and rail. 
    # Consider share of rail transport and country-specific issues with overhead electricity lines for rail system --> larger H2 share
    AB_2030: 0.00
    NZ_2030: 0.00
    AB_2035: 0.01
    NZ_2035: 0.02
    AB_2050: 0.08
    NZ_2050: 0.12

  land_transport_electric_share: # 1 means all EVs  # This leads to problems when non-zero HERE
    NH2S_2030: 0.05 # based on Morocco H2 strategy (reference scenario)
    GNZ_2030: 0.08 # based on IEA scenarios
    NH2S_2050: 0.10 # based on Morocco H2 strategy (reference scenario)
    GNZ_2050: 0.74 # based on IEA scenarios
    MA-NH2S-IEE_2030: 0.05 # based on Morocco H2 strategy (reference scenario)
    MA-GNZ-IEE_2030: 0.08 # based on IEA scenarios
    MA-NH2S-IEE_2050: 0.10 # based on Morocco H2 strategy (reference scenario)
    MA-GNZ-IEE_2050: 0.74 # based on IEA scenarios
    AB_2030: 0.03
    NZ_2030: 0.05
    AB_2035: 0.08
    NZ_2035: 0.12
    AB_2050: 0.45
    NZ_2050: 0.68

  co2_network: true
  co2_sequestration_potential: 200 #MtCO2/a sequestration potential for Europe
  co2_sequestration_cost: 10 #EUR/tCO2 for sequestration of CO2
  hydrogen_underground_storage: true
  shipping_hydrogen_liquefaction: false
  shipping_average_efficiency: 0.4 #For conversion of fuel oil to propulsion in 2011

  shipping_hydrogen_share: #1.0
    NH2S_2030: 0.05 # based on Morocco H2 strategy (reference scenario)
    GNZ_2030: 0.04 # based on IEA scenarios
    NH2S_2050: 0.10 # based on Morocco H2 strategy (reference scenario)
    GNZ_2050: 0.19 # based on IEA scenarios
    MA-NH2S-IEE_2030: 0.05 # based on Morocco H2 strategy (reference scenario)
    MA-GNZ-IEE_2030: 0.04 # based on IEA scenarios
    MA-NH2S-IEE_2050: 0.10 # based on Morocco H2 strategy (reference scenario)
    MA-GNZ-IEE_2050: 0.19 # based on IEA scenarios
  # TODO: Double check for future iterations
  # https://www.iea.org/reports/aviation-and-shipping#dashboard --> we choose lower values compared to IEA because methanol ships are currently ordnered instead of ammonia ships.
  # Share of hydrogen or hydrogen-equivalents of ammonia shipping. Might depend on country and routes.
  # Fischer-tropsch based shipping e-fuel share is result of optimisation and co2limit. Co2L must consider international shipping emissions. --> to be discussed.
    AB_2030: 0.02
    NZ_2030: 0.05
    AB_2035: 0.05
    NZ_2035: 0.10
    AB_2050: 0.25
    NZ_2050: 0.35

  h2_cavern: true
  marginal_cost_storage: 0
  methanation: true
  helmeth: false
  dac: true
  SMR: true
  SMR CC: true
  cc_fraction: 0.9
  cc: true
  space_heat_share: 0.6 # the share of space heating from all heating. Remainder goes to water heating.
  airport_sizing_factor: 3

  min_part_load_fischer_tropsch: 0.0


solving:
  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    gurobi-default:
      threads: 16
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-6
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200